### ISSUE TITLE
Evidence extraction from links

### ISSUE THREAD

**Issue by hoangdzung** [nguyenvo09/EACL2021#1]
Hi. I have a question about how you create the mapped data. In the original dataset, the evidence is only the URLs. How did you extract the text from the webpage? It was a random paragraph or something?
Thank you.

**Comment by nguyenvo09** [comment]
Hi Hoang, 
thank you for your question. I created the mapped data by simply assigning an ID for each claim and evidence. The original datasets are from https://www.mpi-inf.mpg.de/dl-cred-analysis/. They preprocessed the dataset so I simply used it. For more details, you can refer to the link above. 
Thanks.
